### ISSUE TITLE
Mousewheel jumping

### ISSUE THREAD

**Issue by hahiserw** [Warsow/qfusion#26]
I tried to set mwheeldown to jump, but it doesn't work. Jumping only works with with keyboard keys.

However dashing works with mwheel.

**Comment by dnk777** [comment]
Jumping is not an event (an "impulse") contrary to dashing/firing/pressing "use" button, etc, but is considered a movement direction, and a fraction of time when a key has been pressed is used/transferred to a server (and it is zero for mouse wheel events). That's partially because "jump" key is not only for jumping itself, but also for controlling a character in water/in air while having a jetpack. You would observe the same trying to bind other directional movement keys to a mouse wheel.
  
That's the behavior of all quakes, see https://github.com/id-Software/Quake-2/blob/master/client/cl_input.c#L185 for reference.
